### PR TITLE
chore: add cronjob to clean up pipelineruns

### PR DESCRIPTION
**Pull request by theflockers**
this PR adds a new cronjob to the stonesoup-int-srvc namespace to clean up the last day pipelineruns left of finished internal-requests.

### CODE REVIEW

**Review by johnbieren — COMMENTED** [review]
Are we sure we are the only plrs in this namespace? We don't need to use a label selector for release or anything?

**Comment by theflockers** [comment]
> Are we sure we are the only plrs in this namespace? We don't need to use a label selector for release or anything?

As off today yes. We are the only ones using this. But sure, I can make it more specific just in case.

**Comment by theflockers** [comment]
btw, just noticed I did not put it in the right directory.

**Comment by theflockers** [comment]
This needs to be added as well in app-interface, so I am adding both envs as the other configs found in the `config/` directory, although in app-interface they will differ `main`  and `stable` branches.

**Review by johnbieren — COMMENTED** [review]
I know you are following other examples in this repo, but I don't really agree with them - why not to just have one (not staging vs production) and then have the sre mapping for stage clusters consume the main branch and the sre mapping for prod clusters consume the stable branch? Similar to how we do for the tekton resources in this repo (but dissimilar to how we have the signing configmaps set up)

**Comment by theflockers** [comment]
> I know you are following other examples in this repo, but I don't really agree with them - why not to just have one (not staging vs production) and then have the sre mapping for stage clusters consume the main branch and the sre mapping for prod clusters consume the stable branch? Similar to how we do for the tekton resources in this repo (but dissimilar to how we have the signing configmaps set up)

The sre config in app-interface is already using different branches. I will leave a single one then - i like it better too.

**Review by johnbieren — APPROVED** [review]

**Comment by johnbieren** [comment]
Can you squash the commits?

**Comment by theflockers** [comment]
> Can you squash the commits?

done

**Pull request merged**
