### PR TITLE
feat(RELEASE-1283): file-updates updates

### PR DESCRIPTION
**Pull request by scoheb**
* allow file-updates-secret to be configurable
* change reference to RHTAP to Konflux

### CODE REVIEW

**Review by happybhati — APPROVED** [review]

**Comment by johnbieren** [comment]
Why do we need the secret to be configurable?

**Comment by scoheb** [comment]
> Why do we need the secret to be configurable?

Right now, the task is generic in that it can update multiple repos. Each repo may require its own project access token so a single secret may not work. 

In addition, we may want to support creating MR for stage or prod and therefore we might to specify that via the RPA.

**Review by johnbieren — COMMENTED** [review]
Got it. Can you bump the version things? And when the catalog PR is opened for this change (adding the params to the internal request) can you link it to this?

**Review by johnbieren — APPROVED** [review]
I guess the version strings weren't bumped in main and this is stable so doesn't make sense now since we would have a conflict

**Pull request merged**
