### PR TITLE
feat(HACBS-2506): add revert prefix support

### PR DESCRIPTION
**Pull request by Troy876**
Updates gitlint to support "revert" as a prefix

### CODE REVIEW

**Comment by Troy876** [comment]
@theflockers 
@davidmogar 
@mmalina 
@scoheb

**Review by davidmogar — APPROVED** [review]

**Review by mmalina — APPROVED** [review]

**Comment by Troy876** [comment]
Adjusted YAML files to fix yamllint errors
Mind approving the workflow? Thanks

**Comment by mmalina** [comment]
yamllint still fails in many places.

**Comment by Troy876** [comment]
Updating YAML files to align with yamllint is unrelated to HACBS-2506
Simpler to close and reopen a new PR than to try and revert commits

**Pull request closed without merging**
